name: Repository Dispatch

on:
  push:
     branches: [feature/1]
  repository_dispatch:
    types: [new-image]

permissions:
  contents: write  # Ensure the workflow has write permissions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i node-app/deployment.yaml
    
    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"    

    - name: Commit changes    
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes
        branch: feature/1  # Ensure the branch is specified
      env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

#This workflow automatically updates the Docker image version in a Kubernetes deployment file (deployment.yaml) 
#when changes are pushed to the feature/1 branch or when a new-image event is received. 
#It then commits these changes back to the repository. 
#This is crucial for ensuring that the deployment configuration is always up to date with the latest image.          